// =============================================================================
//  codegen.rs — C Code Generator for the hanlin language
// =============================================================================
//
//  Walks the AST and emits valid C source code, which is then compiled by
//  the host's C compiler (gcc/clang) to produce a native binary.
//
//  Design decisions:
//    - All numbers are represented as `double` in C for simplicity.
//    - Booleans are represented as `int` (0 / 1).
//    - Strings are `const char*` literals.
//    - `print(...)` maps to `printf` with auto-detected format specifiers.
//    - Functions are forward-declared before `main` so ordering doesn't matter.
//    - `const` variables are emitted as `const double`.
//
//  Pipeline:
//    Program (AST)  →  CEmitter  →  C source string  →  file  →  gcc  →  binary
// =============================================================================

use crate::ast::{Expr, Literal, Program, Stmt};
use crate::error::Result;

// ---------------------------------------------------------------------------
//  CEmitter
// ---------------------------------------------------------------------------

/// Walks the AST and accumulates C source code into an internal buffer.
pub struct CEmitter {
    /// The accumulated C source code output.
    output: String,
    /// Current indentation level (each level = 4 spaces).
    indent: usize,
}

#[allow(clippy::new_without_default)]
impl CEmitter {
    pub fn new() -> Self {
        CEmitter {
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate and return the complete C source code for a program.
    pub fn emit_program(&mut self, program: &Program) -> Result<String> {
        self.output.clear();

        // ── C file header ────────────────────────────────────────────────
        self.emit_line("// Auto-generated by the hanlin compiler (v0.2.1)");
        self.emit_line("// Do not edit manually.");
        self.emit_line("");
        self.emit_line("#include <stdio.h>");
        self.emit_line("#include <math.h>");
        self.emit_line("#include <string.h>");
        self.emit_line("");

        // ── Forward declarations for all user-defined functions ───────────
        // This allows functions to be called before they are defined in the
        // generated C file (order-independent in hanlin).
        let mut has_forward_decls = false;
        for stmt in &program.body {
            if let Stmt::FnDecl { name, params, .. } = stmt {
                let params_str = if params.is_empty() {
                    "void".to_string()
                } else {
                    params
                        .iter()
                        .map(|p| format!("double {}", p))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                self.emit_line(&format!("double {}({});", name, params_str));
                has_forward_decls = true;
            }
        }
        if has_forward_decls {
            self.emit_line("");
        }

        // ── Emit non-main statements first (function definitions) ─────────
        // Collect top-level statements that are NOT function declarations
        // to put into main().
        let mut main_stmts: Vec<&Stmt> = Vec::new();

        for stmt in &program.body {
            match stmt {
                Stmt::FnDecl { .. } => {
                    self.emit_stmt(stmt)?;
                    self.emit_line("");
                }
                other => main_stmts.push(other),
            }
        }

        // ── Emit the main() function ──────────────────────────────────────
        self.emit_line("int main(void) {");
        self.indent += 1;

        for stmt in &main_stmts {
            self.emit_stmt(stmt)?;
        }

        self.emit_indented("return 0;\n");
        self.indent -= 1;
        self.emit_line("}");

        Ok(self.output.clone())
    }

    // =========================================================================
    //  Statement emission
    // =========================================================================

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<()> {
        match stmt {
            Stmt::VarDecl {
                name,
                is_const,
                init,
                ..
            } => {
                self.emit_var_decl(name, *is_const, init.as_ref())?;
            }
            Stmt::FnDecl {
                name, params, body, ..
            } => {
                self.emit_fn_decl(name, params, body)?;
            }
            Stmt::Return { value, .. } => {
                self.emit_return(value.as_ref())?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
                ..
            } => {
                self.emit_if(condition, then_body, else_body.as_deref())?;
            }
            Stmt::While {
                condition, body, ..
            } => {
                self.emit_while(condition, body)?;
            }
            Stmt::For {
                init,
                condition,
                update,
                body,
                ..
            } => {
                self.emit_for(init.as_deref(), condition.as_ref(), update.as_ref(), body)?;
            }
            Stmt::Break { .. } => {
                self.emit_indented("break;\n");
            }
            Stmt::Continue { .. } => {
                self.emit_indented("continue;\n");
            }
            Stmt::Print { args, .. } => {
                self.emit_print(args)?;
            }
            Stmt::Expression { expr, .. } => {
                let expr_str = self.emit_expr(expr)?;
                self.emit_indented(&format!("{};\n", expr_str));
            }
            Stmt::TryCatch { .. } => {
                return Err(crate::error::HanlinError::codegen(
                    "try-catch is not supported in C code generation (use the interpreter instead)",
                ));
            }
        }
        Ok(())
    }

    // ── Variable declaration ────────────────────────────────────────────────

    fn emit_var_decl(&mut self, name: &str, is_const: bool, init: Option<&Expr>) -> Result<()> {
        let qualifier = if is_const { "const double" } else { "double" };
        match init {
            Some(expr) => {
                let val = self.emit_expr(expr)?;
                // Detect if this is a string expression — strings need `const char*`
                if is_string_expr(expr) {
                    self.emit_indented(&format!("const char* {} = {};\n", name, val));
                } else {
                    self.emit_indented(&format!("{} {} = {};\n", qualifier, name, val));
                }
            }
            None => {
                self.emit_indented(&format!("{} {} = 0;\n", qualifier, name));
            }
        }
        Ok(())
    }

    // ── Function declaration ────────────────────────────────────────────────

    fn emit_fn_decl(&mut self, name: &str, params: &[String], body: &[Stmt]) -> Result<()> {
        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params
                .iter()
                .map(|p| format!("double {}", p))
                .collect::<Vec<_>>()
                .join(", ")
        };

        self.emit_line(&format!("double {}({}) {{", name, params_str));
        self.indent += 1;
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        self.indent -= 1;
        self.emit_line("}");
        Ok(())
    }

    // ── Return statement ────────────────────────────────────────────────────

    fn emit_return(&mut self, value: Option<&Expr>) -> Result<()> {
        match value {
            Some(expr) => {
                let val = self.emit_expr(expr)?;
                self.emit_indented(&format!("return {};\n", val));
            }
            None => {
                self.emit_indented("return 0;\n");
            }
        }
        Ok(())
    }

    // ── If / else ──────────────────────────────────────────────────────────

    fn emit_if(
        &mut self,
        cond: &Expr,
        then_body: &[Stmt],
        else_body: Option<&[Stmt]>,
    ) -> Result<()> {
        let cond_str = self.emit_expr(cond)?;
        self.emit_indented(&format!("if ({}) {{\n", cond_str));
        self.indent += 1;
        for stmt in then_body {
            self.emit_stmt(stmt)?;
        }
        self.indent -= 1;

        if let Some(else_stmts) = else_body {
            self.emit_indented("} else {\n");
            self.indent += 1;
            for stmt in else_stmts {
                self.emit_stmt(stmt)?;
            }
            self.indent -= 1;
        }

        self.emit_indented("}\n");
        Ok(())
    }

    // ── While loop ─────────────────────────────────────────────────────────

    fn emit_while(&mut self, cond: &Expr, body: &[Stmt]) -> Result<()> {
        let cond_str = self.emit_expr(cond)?;
        self.emit_indented(&format!("while ({}) {{\n", cond_str));
        self.indent += 1;
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        self.indent -= 1;
        self.emit_indented("}\n");
        Ok(())
    }

    // ── Print statement ─────────────────────────────────────────────────────
    //
    //  hanlin's `print(a, b, c)` maps to `printf(fmt, a, b, c)\n`.
    //  We auto-detect the format specifier for each argument:
    //    - String literal → %s
    //    - Bool expr      → %d
    //    - Everything else→ %g  (prints floats/ints cleanly, no trailing zeros)

    fn emit_print(&mut self, args: &[Expr]) -> Result<()> {
        if args.is_empty() {
            self.emit_indented("printf(\"\\n\");\n");
            return Ok(());
        }

        let mut fmt_parts = Vec::new();
        let mut arg_exprs = Vec::new();

        for arg in args {
            let (fmt, expr_str) = self.emit_print_arg(arg)?;
            fmt_parts.push(fmt);
            arg_exprs.push(expr_str);
        }

        let fmt_str = fmt_parts.join(" ");

        if arg_exprs.is_empty() {
            self.emit_indented(&format!("printf(\"{}\\n\");\n", fmt_str));
        } else {
            let args_str = arg_exprs.join(", ");
            self.emit_indented(&format!("printf(\"{}\\n\", {});\n", fmt_str, args_str));
        }
        Ok(())
    }

    /// Returns (format_specifier, c_expression_string) for a single print argument.
    fn emit_print_arg(&mut self, arg: &Expr) -> Result<(String, String)> {
        let expr_str = self.emit_expr(arg)?;
        let fmt = match arg {
            Expr::Literal(Literal::Str(_)) => "%s".to_string(),
            Expr::Literal(Literal::Bool(_)) => "%d".to_string(),
            // %g prints doubles without unnecessary trailing zeros
            _ => "%g".to_string(),
        };
        Ok((fmt, expr_str))
    }

    // =========================================================================
    //  Expression emission
    // =========================================================================

    fn emit_expr(&mut self, expr: &Expr) -> Result<String> {
        match expr {
            Expr::Literal(lit) => Ok(self.emit_literal(lit)),

            Expr::Identifier(name) => Ok(name.clone()),

            Expr::Binary { op, left, right } => {
                let l = self.emit_expr(left)?;
                let r = self.emit_expr(right)?;
                // C's % operator requires integer operands — cast double→long for Mod.
                // We use BinOp::as_c_op() for all other operators as-is.
                if matches!(op, crate::ast::BinOp::Mod) {
                    Ok(format!("(double)((long)({}) % (long)({}))", l, r))
                } else {
                    // Wrap in parens to preserve operator precedence in the generated C
                    Ok(format!("({} {} {})", l, op.as_c_op(), r))
                }
            }

            Expr::Unary { op, expr } => {
                let e = self.emit_expr(expr)?;
                Ok(format!("({}{})", op.as_c_op(), e))
            }

            Expr::Assign { name, value } => {
                let val = self.emit_expr(value)?;
                Ok(format!("{} = {}", name, val))
            }

            Expr::Call { callee, args } => {
                let args_str = args.iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{}({})", callee, args_str))
            }

            Expr::ArrayLiteral { .. } |
            Expr::ObjectLiteral { .. } |
            Expr::Index { .. } |
            Expr::Member { .. } |
            Expr::MethodCall { .. } |
            Expr::AssignIndex { .. } |
            Expr::AssignMember { .. } => {
                Err(crate::error::HanlinError::codegen("C code generation does not support advanced JavaScript-like structures (arrays/objects/methods)"))
            }
        }
    }

    fn emit_literal(&self, lit: &Literal) -> String {
        match lit {
            Literal::Integer(n) => format!("{}.0", n), // promote to double
            Literal::Float(f) => format!("{}", f),
            Literal::Str(s) => format!("\"{}\"", escape_c_string(s)),
            Literal::Bool(true) => "1".to_string(),
            Literal::Bool(false) => "0".to_string(),
            Literal::Null => "0".to_string(),
        }
    }

    // =========================================================================
    //  Output helpers
    // =========================================================================

    fn emit_line(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn emit_indented(&mut self, text: &str) {
        let indent_str = "    ".repeat(self.indent);
        for line in text.lines() {
            self.output.push_str(&indent_str);
            self.output.push_str(line);
            self.output.push('\n');
        }
        // Preserve a trailing newline if the text ends with \n
        // (lines() strips trailing newline, so we handle it above)
    }

    // ── For loop ────────────────────────────────────────────────────────────
    //
    //  Emits a scoped C block to keep the init variable from leaking:
    //
    //    {
    //        double i = 0.0;        // init
    //        while (i < 10.0) {    // condition (absent → "while (1)")
    //            <body>
    //            i = i + 1.0;      // update
    //        }
    //    }

    fn emit_for(
        &mut self,
        init: Option<&Stmt>,
        condition: Option<&Expr>,
        update: Option<&Expr>,
        body: &[Stmt],
    ) -> Result<()> {
        // Outer scope for init variable
        self.emit_indented("{\n");
        self.indent += 1;

        // Emit init
        if let Some(init_stmt) = init {
            self.emit_stmt(init_stmt)?;
        }

        // Condition string (absent → always true)
        let cond_str = if let Some(cond) = condition {
            self.emit_expr(cond)?
        } else {
            "1".to_string()
        };

        self.emit_indented(&format!("while ({}) {{\n", cond_str));
        self.indent += 1;

        // Body
        for stmt in body {
            self.emit_stmt(stmt)?;
        }

        // Update expression
        if let Some(upd) = update {
            let upd_str = self.emit_expr(upd)?;
            self.emit_indented(&format!("{};\n", upd_str));
        }

        self.indent -= 1;
        self.emit_indented("}\n");
        self.indent -= 1;
        self.emit_indented("}\n");

        Ok(())
    }
}

// ---------------------------------------------------------------------------
//  Utility functions
// ---------------------------------------------------------------------------

/// Returns true if an expression is guaranteed to produce a string value.
fn is_string_expr(expr: &Expr) -> bool {
    matches!(expr, Expr::Literal(Literal::Str(_)))
}

/// Escape special characters in a string for C string literals.
fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out
}
